server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
        driver-class-name: org.h2.Driver
        password:
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
     console:
         enabled: true
         path: /h2
#Flyway
endpoints:
      logview:
          path: log
      flyway:
          web:
          enabled: true
flyway:
    baseline-on-migrate: true
# Log configuration
logging:
    config: file:logback-spring.xml
#Properties
auth:
   token:
      expiration:
            time: 864000
      validity:
            time: 300
   client:
        id: alpha
        secret: horizon
        scope: read,write
        authorized-grant-types: password,refresh_token,client-credentials
