server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
    oauth2:
        client:
            access-token-validity-seconds: 4800
            authorized-grant-types: password,refresh_token
            client-id: alpha
            client-secret: $2a$10$p9Pk0fQNAQSesI4vuvKA0OZanDD2
            resource-ids: resources
            scope: read,write

spring:
    datasource:
        driver-class-name: org.h2.Driver
        password:
        url: jdbc:h2:mem:testdb
        username: sa
        schema: classpath:/sql/schema.sql
        data: classpath:/sql/data.sql
        
# H2 - Console
# see more: http://www.h2database.com/html/tutorial.html
#Server:{server.port}/{spring.h2.console.path}   -> http:localhost:9092/h2
spring:
      h2:
       console:
            enabled: true
            path: /h2
